Morganamilo/paru

src/main.rs
=> Fix clean argument

help, src/clean.rs, src/command_line.rs, src/config.rs, src/keys.rs, src/main.rs, src/sync.rs, src/util.rs
=> Fix typos and wording

src/install.rs
=> Bail if installing AUR packages as root

Cargo.toml, changes, completions/bash, completions/fish, completions/zsh, help, man/paru.8, man/paru.conf.5, paru.conf, src/command_line.rs, src/config.rs, src/install.rs
added the config option and commandline flag for Devel Suffixes, resolving #19
=> Config opts for Devel Suffixes

src/install.rs, src/search.rs
fixes #14 
Added in filtration to always place exact match at top of list
=> added filter to place exact match at top of list

README.md
The current readme video was clearly recorded on a 4k screen, which, with any standard resolution, makes the file difficult to read in the browser. I re-recorded with the latest version of paru, and made the video at a reasonable resolution, that doesn't overpower the file.
=> Update Readme to contain a more suitable video

man/paru.8
=> Fix a spelling mistake on line 82 of the man page

Cargo.lock, Cargo.toml, README.md, completions/bash, completions/fish, completions/zsh, help, man/paru.8, src/command_line.rs, src/config.rs, src/download.rs, src/main.rs
=> Add AUR comments support

man/paru.conf.5
Yes, this is tiny. Yes it annoyed me enough to make this PR.
=> manpages: Remove dashes from InstallDebug

src/upgrade.rs
=> Fix numbers in upgrade menu being printed improperly for devel packages

man/paru.conf.5
See #123 for the discussion leading to this PR.
=> Remove topdown from `paru.conf(5)`

completions/fish
Fixes issues noticed because of #153
=> Fix tab completion for -a in fish

src/install.rs
=> Don't remove make dependencies when running from chroot

Cargo.lock, Cargo.toml, src/clean.rs, src/config.rs, src/install.rs, src/search.rs
Added globbing to resolve #133
=> Added NoWarn globbing

src/install.rs
=> Adding check for --noconfirm flag on PKGBUILD diff

completions/fish
=> Fix typo in fish completions

help
=> fix help menu: rename --noskipreview -> --review

src/exec.rs
Hopefully this will help some users diagnose their own issues better such as in #206 and #296.
=> Mention sudo_bin if an error occurs calling pacman

src/config.rs, src/devel.rs, src/download.rs, src/install.rs, src/main.rs, src/query.rs, src/remove.rs, src/search.rs, src/sync.rs, src/upgrade.rs, src/util.rs
=> Give Clippy the world.

src/clean.rs
=> Need to make $pkgdir readable, not writeable

completions/bash, completions/fish, completions/zsh, help, man/paru.8, src/command_line.rs, src/config.rs, src/install.rs, src/main.rs, src/stats.rs, src/util.rs
Implement option to show system package statistics (Total installed, Total size, orphaned, ...)
=> Add -P --stats

po/ca.po
Hopefully everything is in place.
=> Add Catalan translation

po/it.po
The only opinionated choice I think I made is to not translate `directory`, since I noticed this is also the case for the Italian translation of `pacman`.
A review would be appreciated if anyone wants to do that
=> Initial upload for Italian translation

po/es.po
Spanish (Spain) localization. 
PD: Thanks for the paru project. Always nice to see more Rusty stuff
=> Add es localization

po/fi.po
Simple translation, some technical terminology (make / devel / snapshot) was left unchanged for clarity over full translation, am open to suggestions if there are any commonly used terms for these!
Tried to follow pacman's own finnish translation for reference on other technical terminology such as repository (pakettivarasto), but in some parts such as "repo package", tried to avoid redundancy of "pakettivarasto paketti" with simpler, "varasto paketti", but am not sure if this should just be replaced by "repo paketti" or something more simple and similar.
=> Finnish translation for paru

po/ru.po
Initial upload, using the pre-existing Chinese PO as a template
=> Create a Russian translation

po/ro.po
I added the Romanian translation, tested it and it works properly. I initially had some problems with testing it because I forgot to change my system locale from en_US to Romanian (posted on the IRC chat, without realizing what was the problem). After I fixed that, paru started displaying the text in my native language with my translations.
=> Add Romanian translation

po/zh_TW.po
I added zh_TW translations, please review and merge it :smiley:
=> Add zh_TW translations.

po/fr.po
- Renumbering of the misaligned translation strings
- Translation of 2 missing strings
- Correction of a few typos and punctuation/capitalisation errors
=> Update the French translation

Cargo.lock, Cargo.toml, man/paru.8, src/search.rs
Allows search the aur using regex
paru -Ssx ^p.ru
=> Add -x/--regex for -Ss

src/download.rs
=> make paru -G return a correct exit code

po/pt_BR.po
Translate message added in v1.9.1
=> pt_BR: Translate --regex

po/ru.po
I made the translation more like pacman and the AUR web interface.
also fixed some oddities here and there.
=> update russian translation

po/hr.pot
Added a Croatian language support
=> Translation: Croatian language

po/zh_CN.po, scripts/mkpot, src/lib.rs
- Update Chinese Simplified translation
- Add src/lib.rs:241 "no operation specified" translation
- scripts/mkpot add `--package-version` argument
=> Update zh_CN translation

man/paru.8
Fix for small typo in the man page.
=> Fixed typo on the man page.

po/pt.po
For commit: 767609cf27ca58d5667ea91ef06655c67042be43
Update Portuguese translation
=> Update pt.po file

src/install.rs
=> fix: upgrade option rebuild

src/upgrade.rs
pacman uses this in their messages, so use it in paru as well for consistency
=> Add triple dots to upgrade search messages

po/nl.po, po/paru.pot
Align help text by modifying spaces, and translate newly added strings
=> Update Dutch translation

po/fr.po
I'd like some peer review before merging since I was unable to test the french .po file myself ( I find the instructions unclear ).
=> Updated French Language

completions/fish, completions/zsh, man/paru.8, man/paru.conf.5, src/command_line.rs, src/config.rs, src/help.rs
Allows to set an alternative URL for the /rpc endpoint.
=> add option/setting "AurRpcUrl"

po/de.po, po/paru.pot
This pull request aims to add missing translations (e.g.: `paru -h`) and update existing ones with tweaked wordings and punctuation.
=> German translation update

src/help.rs
=> Fix --ignoredevel typo

Cargo.lock, Cargo.toml, src/auth.rs, src/config.rs, src/info.rs
=> term_size -> terminal_size

po/es.po
Updated translations and fill missing strings
=> Update es translation

po/hu.po
The Hungarian translation is complete and ready to use
=> Create a Hungarian language file for translation

src/download.rs
Update according to recent repository name changes
fixes #1142
=> update repository names in download.rs

completions/fish
=> Use `__fish_print_pacman_packages` instead of `__fish_print_packages`

po/cs.po
=> Adding Czech translations

Cargo.toml
=> set MSRV (Minimum Supported Rust Version)

src/util.rs
commit af078e8b broke std{in,out} redirection by
cloning the FDs before passing them to dup2.
This commit fixes this by using dup2_std{in,out}
which doesn't require the FDs to be owned.
Fixes: #1413
=> fix(utils): reading arguments from stdin and interactive menu

completions/bash, completions/fish, completions/zsh, src/completion.rs
=> Add pkgbuild pkgs to completion

src/install.rs
=> Fix warning printing
