Cargo.lock, Cargo.toml, src/download.rs
added the functionality to encode the `@` and `+` characters, as referenced in #8
=> Added URL encoding functionality

src/install.rs
Fixes a typo which caused RemoveMake to fail.
=> Fix Typo in remove make depends

src/search.rs
Currently paru -Ss shows results top-down no matter whether the BottomUp option is set or not.
This patch makes it use the same approach the interactive mode already is using to ensure consistency across different paru commands.
=> Order results of -Ss using BottomUp/TopDown

completions/fish, completions/zsh, man/paru.8, man/paru.conf.5
I went through the man pages after noticing that paru.conf(5) said the arguments for a few options (e.g. Redownload, Rebuild) didn't work when entered the way they appear in the man page. I found some typos, capitalization issues and formatting errors and fixed those (hopefully I caught them all). I made quite a few other changes that I think better explain some of the options too. I also tried to bring consistency to a lot of the terms (like AUR, PKGBUILD, pacman, paru). I also changed all the lines that ended in a period because man adds two spaces when that's entered.
Two things I noticed that should stay updated are the headers (at line 2) that should be kept up to date with the release version and the last time the man page was changed. Also, on line 467 of paru.8, there's a mention …
=> Man page improvements

src/install.rs
Some code here would false-flag packages ending in `-debug` as debug packages, even if it is the base name of the package. this fixes that.
=> Removed false-flagging -debug code

Cargo.lock, Cargo.toml, src/install.rs
Some editors such as `vscode` are exec by a bash script.
`Child.wait()` received a exit code from bash, but vscode is still running.
And the TempDir(`config.fetch.make_view()`) is delete when it goes out of scope.
Then, editor cannot found TempDir.
So, ask `"Proceed with installation?"` in it's scope.
=> install.rs: Fix not compatible with some editors

src/search.rs, src/upgrade.rs, src/util.rs
* Added example for "Packages for exclude" user input
Before:
```
:: Packages to exclude: 
```
After:
```
:: Packages to exclude: (eg: "1 2 3", "1-3")
```
* Added a new line after user input in function `input()`
This is pretty visible on a smaller terminal wight
Before:
```
:: Packages to exclude: (eg: "1 2 3", "1-3") 
```
After:
```
:: Packages to exclude: (eg: "1 2 3", "1-3")
:: 
```
=> Add example for "Packages for exclude" user input

Cargo.toml
| File             | Size (Byte)  |
| -------          | ------------ |
| .gitignore       | 19           |
| dist             | 185          |
| paru.conf        | 383          |
| completions/bash | 4027         |
| help             | 4396         |
| man/paru.conf.5  | 8188         |
| completions/fish | 15081        |
| man/paru.8       | 15162        |
| completions/zsh  | 18336        |
Saved 24% or 65.8 KB in 9 files (of 276.0 KB and 32 files in entire crate)
=> cargo diet: recude crate size on crates.io

Cargo.lock, Cargo.toml, paru.conf, src/chroot.rs, src/command_line.rs, src/config.rs, src/devel.rs, src/download.rs, src/exec.rs, src/install.rs, src/main.rs, src/remove.rs, src/repo.rs, src/search.rs, src/sync.rs, src/upgrade.rs, src/util.rs
This PR adds support for both local repos and building in a clean chroot.
Local repo support can be enabled via the `LocalRepo` option in paru.conf or via the `--localrepo` flag. When this option is enabled, all local repos will enabled by paru. The first one will be where paru builds new packages. However if a package already exists in another local repo, then paru will build it there.
The local repo option also supports taking a list of repos to use. For example `LocalRepo = aur git foo` will cause paru to recognise these local repos. Only building/checking for updates in these repos. Again, the first repo will be where paru builds new packages.
If there are no local repos configured, paru will suggest you add one to your pacman.conf. It will not do this for you. However paru will …
=> Local repo and chroot support

.github/workflows/build.yml, Dockerfile
This adds much-needed automation for release files for both x86_64 and aarch64. This should resolve #117, at least in the sense that the AUR packages will now have paru-bin candidates for aarch64. an issue in the docker/qemu/cargo setup on github/rust/docker's side means that it's not currently possible to get 32 bit ARM builds running, but I have offered (to @Morganamilo) to manually compile these files on a semi-automated way on my own buildserver, and get those files to her to enable earlier than the 3B+ Rasberry pis and other ARM based devices to download binaries at least.
=> Added github actions profiles based on Jguer's work

dist
By default, shell script will continue to execute the next command even if the previous command exited with non-zero status.
=> Make sure the script fails when a command fails

man/paru.8
This mistake seems to have been introduced in e54d6353852d5f9c4b0cdba296d6082e8ff7867c ([file diff](https://github.com/Morganamilo/paru/commit/e54d6353852d5f9c4b0cdba296d6082e8ff7867c#diff-8536eaa31b07ab3d4a95ea757cfebc64f510093c3600ada8422405fb79efee34R262)).
=> man(paru): Remove irrelevant text under entry for --completioninterval

src/install.rs
.SRCINFO is being displayed during the initial review after 9830c7478b1a8f8b1714e0c9cbdc8da516ab8630, this corrects the if.
=> Fix ignore of .SRCINFO during initial review

completions/zsh
Looks like there was a typo made in a6c85111e4d0437652c7ae570622ce38d9aa431b when adding zsh completion.
=> Fixed a typo in zsh completion file

src/clean.rs, src/command_line.rs, src/config.rs, src/download.rs, src/install.rs, src/main.rs, src/query.rs, src/search.rs, src/sync.rs, src/upgrade.rs, src/util.rs
This pull converts most of the string values in the `Config` struct to use enums instead and introduces a trait (`ConfigEnum`) for unified parsing/validating. 
I tried hard to change as little as possible and leave all semantics intact. There's one intended change in behavior as a result of this pull: Previously the config parsing code would accept only `all` or `no` values for some options from the config file while commandline processing allowed `all`, `yes` and `no`. This change will allow `yes` in the config also. If there's a reason to forbid setting `yes`  then I can make an adjustment, but I wasn't even sure the restriction was intentional.
So why is this approach preferable to the current one?
1. The typechecker will protect you against many issues when dealing with those values …
=> Use enums instead of strings for most values in the Config struct.

src/clean.rs
Because `keep_installed` and `keep_current` return `Ok(())`, `clean_untracked()` never runs.
So, the actual result is different from that in the manpage.
> -Sc    Paru will also clean cached AUR packages and any untracked files in the cache.
=> fix(src/clean.rs): -Sc not clean untracked files

src/command_line.rs
The short global pacman flags were not using the given value resulting in paru setting the respective paths to an empty string which caused a `error: failed to initialize alpm: root=/ dbpath=: could not find or read directory` crash.
=> Fix '-r' and '-b' crashing paru

po/nl.po
I currently have some local-only packages installed and the dutch (nl_NL) translation for it lacks a space and colon.
=> nl_NL: Add missing whitespace in translation

src/exec.rs
related to #491.
callers of `makepkg_output` never actually provide `--verifysource -Ccf`, but rather `--printsrcinfo` or `--packagelist`
Print the actual `args` instead.
=> Improve error message for failing makepkg command

man/paru.8, man/paru.conf.5
When running `man paru > /dev/null` or `man paru.conf > /dev/null`, the system reports
```
troff: <standard input>:1: name expected (got '\ '): treated as missing
```
The culprit appears to be the first line in the paru.8 & paru.conf.5 files. This PR fixes this problem.
=> update paru.8 & paru.conf.5 to suppress troff warning

src/config.rs
When running commands like `pacman -Qu`, pacman prints the upgrade text in green and bold, while paru currently only prints it in green. This very very minor commit fixes that disparity.
=> [Minor] Make upgrade text bold (to match pacman)

src/install.rs
Using `sh -c` to execute the PreBuildCommand adds environment variable and `~` (home) expansion in the command, as well as basic (single-line) shell scripting support.
Closes #554
=> Use `sh -c` to execute PreBuildCommand

po/es.po
Adds a missing space when showing available flags in spanish. Sorry I didn't see it sooner.
=> Fix alignment for comments flag

man/paru.8, src/command_line.rs, src/config.rs, src/help.rs
Implement a new `-e` or `--editable` flag to download AUR packages using
SSH.
Fixes #399
=> Implement flag to download AUR packages via SSH

man/paru.conf.5
Fix two small typos in the `paru.conf` man page.
=> Fix typos in paru.conf man page

completions/fish
fish can't complete `paru --s` to `paru --sync` caused by this
* I didn't test all cases
=> fix: typo in fish completion

completions/fish
- fix: lost `-L --repoctl` detection in fish comp
- fix: also for `-C --chrootctl
- fix: incorrect completion inherited from yay
=> fix: `-L -C` detection and incorrect inherited from yay

po/ca.po, po/de.po, po/es.po, po/fi.po, po/fr.po, po/hi.po, po/hr.po, po/it.po, po/ja.po, po/ko.po, po/nl.po, po/paru.pot, po/pt.po, po/pt_BR.po, po/ro.po, po/ru.po, po/sv.po, po/tr.po, po/zh_CN.po, po/zh_TW.po, src/keys.rs
This PR removes an extra bracket added in commit [5b1ff38b0357844193ca7accd2fcf6b13fb4802f](https://github.com/Morganamilo/paru/commit/5b1ff38b0357844193ca7accd2fcf6b13fb4802f#diff-dd5ba1bca5a2e982ec6f7d24bac5d1b5588e12912d838585931ce9547411cccbR47).
PS: I used `sed` to fix the strings, let me know if I have to use `xtr` instead for the translation files.
=> Fix typo in import GPG keys string

man/paru.8, man/paru.conf.5
Proposed in https://github.com/tuna/issues/issues/1424 and [announced officially](https://mirrors.tuna.tsinghua.edu.cn/news/remove-aur/), the AUR mirror at TUNA has retired for months. The URL clearly does not work any longer, so better removal than confusions for now.
=> Remove the outdated description of AurUrl

man/paru.8
Missing `.TP`'s were causing some options to be incorrectly indented.
=> Fix man page typos

src/install.rs
Fixes #832.
I'm not sure whether sorting is actually necessary here or whether `actions` is already sorted. If it _is_ already sorted, please let me know so I can remove that line (or remove it yourself if you don't want to wait for me—I'm leaving "Allow edits by maintainers" enabled).
=> Prevents crashing due to repeated symlinks

src/config.rs
This addresses #231 by setting `devel_path` to `$XDG_STATE_HOME` and moving
existing `devel.json` files from the cache dir to the new location.
This is basically just an updated version of [this pr](https://github.com/Morganamilo/paru/pull/508) which didn't use
`$XDG_STATE_HOME` since it was unsupported in dirs at the time.
=> Move devel.json to $XDG_STATE_HOME

Cargo.lock, Cargo.toml, src/download.rs
New minor versions of nix and indicarif were released. This commit updates them to the current version. All dependencies are then up-to-date as of writing.
=> Bump indicatif and nix deps

src/config.rs, src/devel.rs
Create and initialize the devel file if it does not exist and the old devel file does not exist as well.
solves #889
=> Create and initialize the devel file

src/config.rs
Fixes an issue where `paru -Sc` would run pacman without root permissions, resulting in
> `error: you cannot perform this operation unless you are root.`
=> Fix no sudo when running paru -Sc

README.md
This PR adds a clickable hyperlink to Libera Chat in the IRC section of the README.
=> Add hyperlink to Libera Chat in README.md

src/config.rs
The default value of `Provides` should be `Yes` according to the manual and the parsing logic.
https://github.com/Morganamilo/paru/blob/257e01155501e3f93ed218f3853156a030b20c58/man/paru.conf.5#L105
https://github.com/Morganamilo/paru/blob/257e01155501e3f93ed218f3853156a030b20c58/src/config.rs#L1042
This might fix https://github.com/Morganamilo/paru/issues/747#issuecomment-1527014428 .
=> Fix the default value of `Provides`

src/exec.rs
`paru` fails when trying to spawn a `sudo pacman` child process (`isatty()` returns false) so I let the child inherit stdin to solve the bug.
=> Let child pacman process inherit stdio

man/paru.conf.5
https://github.com/Morganamilo/paru/commit/75f46a8a6b047dc8b197cb5832cbe59a8d683dfc caused `man paru.conf` to not display propely (flags not visible in output)
=> Man for paru.conf didn't display properly

Cargo.lock, Cargo.toml, src/download.rs
Resolves #931
An API from AUR would, of course, be more convenient, but it is what it is.
Bonus: just like `kuchiki`, `scraper` is just a front-end for `html5ever` & `cssparser` (but a newer version of it), so not much has changed in terms of dependencies.
=> kuchiki -> scraper

src/clean.rs
I recently installed a package from the AUR that `srcinfo.rs` failed to parse the `.SRCINFO` of. As a result, when I attempted to clean the caches (with `paru -Sc`), I get an error message of the parse failure, but there is no indication of which package the error originated from. This PR adds that information to the output.
=> Add printing of which package failed to clean in aur cache

completions/bash, completions/fish, completions/zsh, man/paru.8, man/paru.conf.5, src/chroot.rs, src/command_line.rs, src/config.rs, src/install.rs
These flags can be used to configure ccache for chroot.
See https://wiki.archlinux.org/title/ccache#makechrootpkg for details.
Example configuration:
```
[env]
CCACHE_DIR=/ccache
[bin]
ChrootFlags = -d /home/mike/.cache/ccache:/ccache
```
Related: https://github.com/Morganamilo/paru/issues/983#issuecomment-1657115394
=> Add chrootflags option

src/install.rs
Fix #1093
paru should always retrieve package info from local package database instead of aur repo.
=> Aur packages could be installed as needed

src/devel.rs
This PR makes the `failed to create state directory` error display the proper directory, as it can be quite confusing when it happens.
=> Fix cache_dir instead of state_dir in error message

src/config.rs
`std::io::IsTerminal` was stabilized in Rust 1.70.0
=> Replace nix::unistd::isatty with std::io::IsTerminal

scripts/mkmo
When POSIXLY_CORRECT is set, msgfmt requires options to be specified before the po files (as also defined in its man).
=> scripts/mkmo: switch msgfmt args

src/exec.rs
Discussion in #613 finally builds with std rust
maybe it is better to separate removing dependencies.
=> remove once_cell::sync::Lazy for std::sync::LazyLock

Cargo.toml
https://doc.rust-lang.org/std/sync/struct.LazyLock.html
```
warning: current MSRV (Minimum Supported Rust Version) is `1.78.0` but this item is stable since `1.80.0`
--> src/exec.rs:28:52
|
28 | static CAUGHT_SIGNAL: LazyLock<Arc<AtomicUsize>> = LazyLock::new(|| {
|                                                    ^^^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#incompatible_msrv
```
sorry already need to update that
=> update MSRV to 1.80 due to LazyLock

src/download.rs
fixes #1105
added the missing  ! in `!no_warn` block for ood and orphaned. 
refactored the whole method, removed unwraps and improved readability.
=> fix and refactor cache_info_with_warnings

src/args.rs
Running `paru -Syu --sysroot foo` results in this pacman call: `sudo pacman --sync -y -u --sysroot=foo --sysroot=foo --`
This seems to be caused by `"sysroot"` being contained in both, `PACMAN_FLAGS` and `PACMAN_GLOBALS`:
https://github.com/Morganamilo/paru/blob/93d7e7652526765891f61581d13ce0c20cbfe379/src/args.rs#L6
https://github.com/Morganamilo/paru/blob/93d7e7652526765891f61581d13ce0c20cbfe379/src/args.rs#L88
This causes `arg.is_pacman_global()` _and_ `arg.is_pacman_arg()` to return true, adding `"sysroot"` to `self.args.args` twice:
https://github.com/Morganamilo/paru/blob/93d7e7652526765891f61581d13ce0c20cbfe379/src/command_line.rs#L142C1-L158C10
This behavior doesn't seem to cause errors, but also doesn't seem to make sense. It's probably a minor bug. I'm not entirely sure, but …
=> Fix duplicate `--sysroot` argument
